name: Validate
on:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: false
      builder_image:
        type: string
        required: true
      image:
        type: string
        required: true
    secrets:
      AWS_ROLE_ARN:
        required: true

env:
  K6_TIMESTREAM_DATABASE_NAME: github-xk6-output-timestream-${{ inputs.git_ref  || github.sha }}
  K6_TIMESTREAM_TABLE_NAME: test
  INFRA_STACK_NAME: github-xk6-output-timestream-${{ inputs.git_ref  || github.sha }}
  ENV: ci

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-22.04
    environment: Test
    container:
      image: ${{ inputs.builder_image }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - run: make deploy-infra

  test:
    runs-on: ubuntu-22.04
    environment: Test
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Login ghcr.io
        shell: bash
        run: docker login --username ${{ github.repository_owner }} --password ${{ github.token }} ghcr.io
      - run: make FULL_IMAGE_NAME=${{ inputs.image }} test-integration
    needs:
      - deploy-infra

  destroy-infra:
    runs-on: ubuntu-22.04
    environment: Test
    container:
      image: ${{ inputs.builder_image }}
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - run: make destroy-infra
    needs:
      - deploy-infra
      - test
    if: ${{ always() }}
