name: Build on Push (main)
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  prepare:
    uses: ./.github/workflows/_prepare.yaml

  validate:
    uses: ./.github/workflows/_validate.yaml
    with:
      builder_image: ${{ needs.prepare.outputs.ci_builder_image }}
    needs:
      - prepare

  build:
    uses: ./.github/workflows/_build.yaml
    with:
      # Seems to need the CI container on Github Actions rather
      # than just the builder image :(
      builder_image: ${{ needs.prepare.outputs.ci_builder_image }}
    needs:
      - prepare

  build-grafana:
    uses: ./.github/workflows/_build-grafana.yaml

  integration:
    uses: ./.github/workflows/_integration.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      builder_image: ${{ needs.prepare.outputs.ci_builder_image }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    needs:
      - prepare
      - build

  integration-cross-region:
    uses: ./.github/workflows/_integration.yaml
    with:
      image: ${{ needs.build.outputs.image }}
      builder_image: ${{ needs.prepare.outputs.ci_builder_image }}
      region: eu-west-1
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    needs:
      - prepare
      - build

  release:
    uses: ./.github/workflows/_release.yaml
    with:
      builder_image: ${{ needs.prepare.outputs.ci_builder_image }}
    secrets:
      SSH_KEY_GITHUB: ${{ secrets.SSH_KEY_GITHUB }}
    needs:
      - prepare
      - build
      - validate
      - integration
      - integration-cross-region
